# -*- coding: utf-8 -*-
"""flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2Eca4-Qt06KQ0lLiB4jxXlPJR-q0roM
"""

!pip install flask_ngrok
!pip install pyngrok==4.1.1

from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def home():
  return "<h1>김구름 김구름</h1>"

app.run()
#https://www.youtube.com/watch?v=0dYsZt8-nXk&list=PLTUSGW0o2A2FgYB43QuL6wxnUM4dUr1n3 6분 44초 autotoken 부터 하기
